[[cells]]
name = "auth"
enable_type_id = false
location = { file = "../../deps/auth" }

[[cells]]
name = "funding-lock"
enable_type_id = true
location = { file = "../../build/release/funding-lock" }

[[cells]]
name = "commitment-lock"
enable_type_id = true
location = { file = "../../build/release/commitment-lock" }

[lock]
code_hash = "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8"
args = "0x64257f00b6b63e987609fa9be2d0c86d351020fb"
hash_type = "type"
